name = "OptimLBFGSB"
uuid = "412346db-de1d-411a-bb81-66d71c3bf844"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "0.1.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
L_BFGS_B_jll = "81d17ec3-03a1-5e46-b53e-bddc35a13473"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
DocStringExtensions = "0.8"
L_BFGS_B_jll = "3.0.1"
NLSolversBase = "7.3.1"
Optim = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
